"""
Django settings for Fitness_Club project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e1@xn_&0c8-g5+clbo6u&txgk%687lfq7$t&pbl886h!(kkgnf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'drf_yasg',
    'django.contrib.admin',
    'fitness_app',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'django_celery_beat',     
    'django_celery_results',
    'rest_framework',
    'rest_framework_simplejwt',

    

]




MIDDLEWARE = [
     "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React CRA ka port
    "http://localhost:5173",
]

ROOT_URLCONF = 'Fitness_Club.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fitness_Club.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Fitness_clubs',
        'USER': 'root',
        'PASSWORD': 'faizan123@A1',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

INSTALLED_APPS += ['social_django']

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  # Google OAuth2
    'django.contrib.auth.backends.ModelBackend', # keep default auth
)








# OAuth2 provider (Hospital App) credentials
SOCIAL_AUTH_HOSPITAL_KEY = 'rrVvW1opBNpggHQyXh2VF7jKsPhqFxdGHENWlc26'
SOCIAL_AUTH_HOSPITAL_SECRET = 'VQKxwNqsorX0UgCtt205nwZ9gyxudNCYxhtr6IGlaQ5eIPX6dXdqZMoaKnZ5NwxbmWh0thBhjI3r3K4W2ihLu8zo9N4XJVeXhVR5oVn3a6qWiFKISMIem3biChg43WJ8'

# Hospital OAuth endpoints
SOCIAL_AUTH_HOSPITAL_AUTHORIZATION_URL = 'http://localhost:8001/o/authorize/'
SOCIAL_AUTH_HOSPITAL_ACCESS_TOKEN_URL = 'http://localhost:8001/o/token/'

# Optional: user info endpoint if you have one
SOCIAL_AUTH_HOSPITAL_USER_INFO_URL = 'http://localhost:8001/api/userinfo/'

# Scope for access
SOCIAL_AUTH_HOSPITAL_SCOPE = ['read'] 
SOCIAL_AUTH_HOSPITAL_USER_INFO_URL = 'http://localhost:8001/api/userinfo/'



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
] 



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/' 


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' 


RREST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # default
    ),
}

HMS_URL = os.getenv("HMS_URL")


CORS_ALLOW_ALL_ORIGINS = True


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'TIMEOUT': 300,  # 5 minutes
    }
}


# ─── Redis as Broker ───────────────────────────────
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# ─── Results MySQL me store honge ──────────────────
CELERY_RESULT_BACKEND = 'django-db'

# ─── Serialization ─────────────────────────────────
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# ─── Timezone ──────────────────────────────────────
CELERY_TIMEZONE = 'Asia/Karachi'

# ─── Beat Scheduler ────────────────────────────────
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler' 



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}


from datetime import timedelta 


SIMPLE_JWT={
    "ACCESS_TOKEN_LIFETIME":timedelta(minutes=10) ,
    "REFRESH_TOKEN_LIFETIME":timedelta(days=2) ,

}








TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER') 








# settings.py
SENDGRID_API_KEY = "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"  # jo tumne create kiya
EMAIL_FROM = "faizannoorani19@gmail.com"         # verified sender email  

