# Generated by Django 5.2.4 on 2025-12-11 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Centre_name', models.CharField(max_length=30)),
                ('Centre_address', models.CharField(max_length=40)),
                ('phone_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_no', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('Start_date', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Max_participant', models.IntegerField()),
                ('No_of_sessions', models.IntegerField()),
                ('Class_cost', models.FloatField()),
                ('Centre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.class')),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facility_room_no', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('Capacity', models.IntegerField()),
                ('centre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facilities', to='fitness_app.centre')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='Facility_room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.facilities'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Member_id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=40)),
                ('Joined_date', models.DateField()),
                ('Phone_no', models.IntegerField(unique=True)),
                ('Home_Centre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.centre')),
                ('classes', models.ManyToManyField(through='fitness_app.Enrollment', to='fitness_app.class')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='fitness_app.member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.member'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=40)),
                ('Phone_no', models.IntegerField(unique=True)),
                ('joined_date', models.DateTimeField()),
                ('Staff_Role', models.CharField(choices=[('A', 'Administration'), ('C', 'Cleaner'), ('D', 'Instructor Dry'), ('P', 'Instructor Pool'), ('M', 'Manager'), ('S', 'Sales'), ('T', 'Security')], max_length=40)),
                ('Centre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.centre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fitness_Asessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asessment_date', models.DateField()),
                ('vo2_max', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('Weight', models.FloatField()),
                ('BMI', models.FloatField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.member')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.staff')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='instruct_by',
            field=models.ManyToManyField(to='fitness_app.staff'),
        ),
        migrations.AddField(
            model_name='centre',
            name='Manager_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_centre', to='fitness_app.staff'),
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff')], max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('class_no', 'member_id')},
        ),
    ]
