# Generated by Django 6.0.3 on 2026-04-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_alter_signup_confirm_password_alter_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
